* ukotoku
Convert files from audio formats to image formats and back.
** Supported formats
*** Image formats
**** [[https://en.wikipedia.org/wiki/JPEG][JPEG]] (8-bit unsigned only)
**** [[https://en.wikipedia.org/wiki/Portable_Network_Graphics][PNG]] (8-bit unsigned only)
**** [[https://en.wikipedia.org/wiki/TIFF][TIFF]] (8-bit unsigned and 16-bit signed)
*** Audio formats
**** [[https://en.wikipedia.org/wiki/WAV][WAV]]
** Requirements
*** Python
This script has only been tested with Python 3.6
*** Python modules
**** [[https://pypi.org/project/click/][click]]
**** [[https://imageio.github.io][imageio]]
**** [[https://numpy.org/][numpy]]
** Installation
*** Install the Python modules listed above
#+BEGIN_SRC sh
pip3 install --user click
pip3 install --user imageio
pip3 install --user numpy
#+END_SRC
*** Clone this git repo
#+BEGIN_SRC sh
git clone https://github.com/diamond-lizard/ukotoku.git
#+END_SRC
** Use
#+BEGIN_SRC sh
ukotoku OPTIONS INPUT OUTPUT
#+END_SRC
*** INPUT
The name of the file you want to convert from.
*** OUTPUT
The name of the file that you want INPUT to be converted to.
*** Required options for audio output
**** For the WAV format:
***** --channels  INTEGER
The number of channels the WAV file is to have (ex: "1" for mono, "2" for stereo, etc)
***** --sampwidth INTEGER
The sample width the WAV file is to have (ex: "2")
****** NOTE: You should use a sample width of "1" for 8-bit WAVs, "2" for 16-bit WAVs, etc
****** NOTE: You should use a sample width of at least 2 (16-bit) if you wish to ensure that all the data in the TIFF is preserved in the WAV.
***** --samprate  INTEGER
The sample rate the WAV file is to have (ex: "44100")
*** Required options for image output
**** --resolution WIDTH,HEIGHT or 'guess'
***** x and y image dimensions
***** If you choose 'guess', then ukotoku will try to set the image size to a square equal to or slightly larget than the data will fit in to.
**** --bits
***** Bit depth.
Currently 8 bits is the only supported format for JPEG and PNG output.  8 or 16 bits are supported for TIFF.
**** --signed or --unsigned
***** Unsigned bits are all positive, while signed bits can be positive or negative.
Currently unsigned is the only supported format for JPEG and PNG output.  8 or 16 bits are supported for TIFF.
** Examples
*** Convert from a TIFF file to a WAV file
*Note: The resulting WAV file will be in mono, 16-bit bit depth, and 22050 sample rate.*
#+BEGIN_SRC sh
ukotoku --channels 1 --sampwidth 2 --samprate 22050 INPUT.tiff OUTPUT.wav
#+END_SRC
*** Convert from a WAV file to a TIFF file
*Note: The resulting TIFF file will be 163 pixels wide by 163 pixels high.*
#+BEGIN_SRC sh
ukotoku --resolution 163x163 INPUT.tiff OUTPUT.wav
#+END_SRC
** FAQ
*** I converted from an image to an audio file and back (or vice versa) but the result isn't exactly like the original.
To ensure that a bidirectional conversion is lossless you have to:
**** Use lossless file formats (like WAV and TIFF).
**** Have enough bit-depth to fit the data without clipping (ie. exceeding the limits of the format, aka "clipping")
**** Use the same settings on the return conversion as the original had
**** For example, if you wanted to convert a grayscale 1024x768 image to audio and back without loss of information:
***** The original image should be saved in a lossless image format like TIFF
***** The original image should have at a bit depth of at least 16-bits
***** When converting from image to audio, ukotoku should be told to convert it to a lossless audio format like WAV of at least 16-bits
***** When converting back from audio to image, ukotoku should be told to convert it to an image of the same resolution as the original
*** Why did you call it ukotoku instead of a more reasonable name like wav2tiff, image2audio, audio2image, or tiff2wav?
They're all taken, more limiting, and not as fun or memorable.
** Testing:
This script was only tested with Python 3.6 on amd64 Gentoo Linux
** Bug reports
Report bugs here:  https://github.com/diamond-lizard/ukotoku/issues
** Alternatives
*** [[https://github.com/hackerfriendly/wav2tiff][hackerfriendly/wav2tiff]]
*** [[https://github.com/niland/wav2image][niland/wav2image]]
** LICENSE
Copyright (C) 2020 - Sergey Goldgaber

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
